/**
 * src/services/mockData.js
 * Comprehensive mock data engine for the Food Inspection Monitor platform.
 * Provides realistic initial data for businesses, inspections, inspectors,
 * safety alerts, analytics, reports, and user management.
 */

export const INITIAL_BUSINESSES = [
  {
    id: 'BUS-1001',
    name: 'Gourmet Bistro & Grill',
    type: 'Fine Dining Restaurant',
    licenseNo: 'LIC-2024-8831',
    owner: 'Marcus Vance',
    email: 'contact@gourmetbistro.com',
    phone: '+1 (555) 234-5678',
    address: '452 Downtown Plaza, District 1',
    district: 'Downtown District',
    riskLevel: 'HIGH',
    status: 'ACTIVE',
    healthScore: 94,
    grade: 'A',
    lastInspectionDate: '2026-07-15',
    nextInspectionDate: '2026-10-15',
    totalInspections: 12,
  },
  {
    id: 'BUS-1002',
    name: 'Golden Dragon Express',
    type: 'Fast Casual Chinese',
    licenseNo: 'LIC-2024-9942',
    owner: 'Mei Ling Chen',
    email: 'info@goldendragon.com',
    phone: '+1 (555) 345-6789',
    address: '118 Chinatown Ave, District 2',
    district: 'Eastside District',
    riskLevel: 'HIGH',
    status: 'WARNING',
    healthScore: 74,
    grade: 'C',
    lastInspectionDate: '2026-07-28',
    nextInspectionDate: '2026-08-10',
    totalInspections: 18,
  },
  {
    id: 'BUS-1003',
    name: 'Fresh Harvest Organics',
    type: 'Grocery & Deli',
    licenseNo: 'LIC-2023-1102',
    owner: 'Sarah Jenkins',
    email: 'admin@freshharvest.org',
    phone: '+1 (555) 456-7890',
    address: '890 Green Valley Rd, District 3',
    district: 'Northside District',
    riskLevel: 'MEDIUM',
    status: 'ACTIVE',
    healthScore: 98,
    grade: 'A',
    lastInspectionDate: '2026-06-20',
    nextInspectionDate: '2026-12-20',
    totalInspections: 8,
  },
  {
    id: 'BUS-1004',
    name: 'Taco Haven Food Truck',
    type: 'Mobile Food Unit',
    licenseNo: 'LIC-2025-0012',
    owner: 'Carlos Rodriguez',
    email: 'carlos@tacohaven.io',
    phone: '+1 (555) 567-8901',
    address: 'Mobile Unit - Location #4 (Waterfront)',
    district: 'Harbor District',
    riskLevel: 'HIGH',
    status: 'ACTIVE',
    healthScore: 88,
    grade: 'B',
    lastInspectionDate: '2026-07-10',
    nextInspectionDate: '2026-09-10',
    totalInspections: 6,
  },
  {
    id: 'BUS-1005',
    name: 'Artisan Bread Bakery',
    type: 'Bakery & Cafe',
    licenseNo: 'LIC-2024-4410',
    owner: 'Elena Rostova',
    email: 'hello@artisanbread.com',
    phone: '+1 (555) 678-9012',
    address: '304 Bakery Lane, District 1',
    district: 'Downtown District',
    riskLevel: 'LOW',
    status: 'ACTIVE',
    healthScore: 96,
    grade: 'A',
    lastInspectionDate: '2026-05-14',
    nextInspectionDate: '2026-11-14',
    totalInspections: 5,
  },
  {
    id: 'BUS-1006',
    name: 'Ocean Catch Seafood Shack',
    type: 'Seafood Market & Diner',
    licenseNo: 'LIC-2023-7721',
    owner: 'Captain Ray Sterling',
    email: 'ray@oceancatch.com',
    phone: '+1 (555) 789-0123',
    address: '12 Pier St, District 4',
    district: 'Harbor District',
    riskLevel: 'HIGH',
    status: 'SUSPENDED',
    healthScore: 58,
    grade: 'F',
    lastInspectionDate: '2026-07-29',
    nextInspectionDate: '2026-08-05',
    totalInspections: 22,
  },
  {
    id: 'BUS-1007',
    name: 'Sunrise Coffee & Pastry',
    type: 'Coffee Shop',
    licenseNo: 'LIC-2025-3329',
    owner: 'Hannah Abbott',
    email: 'hannah@sunrisecoffee.com',
    phone: '+1 (555) 890-1234',
    address: '501 University Ave, District 3',
    district: 'Northside District',
    riskLevel: 'LOW',
    status: 'ACTIVE',
    healthScore: 92,
    grade: 'A',
    lastInspectionDate: '2026-07-02',
    nextInspectionDate: '2027-01-02',
    totalInspections: 4,
  },
];

export const INITIAL_INSPECTIONS = [
  {
    id: 'INS-2026-099',
    businessId: 'BUS-1006',
    businessName: 'Ocean Catch Seafood Shack',
    inspectorName: 'Officer David Kim',
    inspectorId: 'USR-INSP-01',
    type: 'Emergency Re-inspection',
    date: '2026-07-29',
    time: '14:30',
    status: 'FAILED',
    score: 58,
    grade: 'F',
    riskCategory: 'HIGH',
    summary: 'Critical cold storage malfunction & cross-contamination detected.',
    violations: [
      { code: 'V-102', severity: 'CRITICAL', description: 'Walk-in freezer temp at 48°F (req. <= 38°F).' },
      { code: 'V-204', severity: 'MAJOR', description: 'Raw seafood stored above ready-to-eat produce.' },
      { code: 'V-301', severity: 'MINOR', description: 'Missing paper towels at staff handwashing sink.' }
    ],
    correctiveActionRequired: 'Immediate emergency closure until temperature system repair verification.',
  },
  {
    id: 'INS-2026-098',
    businessId: 'BUS-1002',
    businessName: 'Golden Dragon Express',
    inspectorName: 'Officer Sarah Connor',
    inspectorId: 'USR-INSP-02',
    type: 'Routine Inspection',
    date: '2026-07-28',
    time: '11:15',
    status: 'WARNING',
    score: 74,
    grade: 'C',
    riskCategory: 'HIGH',
    summary: 'Inadequate food temperature monitoring during peak lunch service.',
    violations: [
      { code: 'V-108', severity: 'MAJOR', description: 'Hot hold buffet counter temp measured at 122°F (req. >= 135°F).' },
      { code: 'V-402', severity: 'MINOR', description: 'Grease accumulation near exhaust hood filters.' }
    ],
    correctiveActionRequired: 'Re-inspection scheduled in 14 days.',
  },
  {
    id: 'INS-2026-097',
    businessId: 'BUS-1001',
    businessName: 'Gourmet Bistro & Grill',
    inspectorName: 'Officer David Kim',
    inspectorId: 'USR-INSP-01',
    type: 'Annual Routine',
    date: '2026-07-15',
    time: '09:45',
    status: 'PASSED',
    score: 94,
    grade: 'A',
    riskCategory: 'HIGH',
    summary: 'Excellent sanitation practices and spotless food prep surfaces.',
    violations: [
      { code: 'V-405', severity: 'MINOR', description: 'Floor tile chip near prep table needs repair.' }
    ],
    correctiveActionRequired: 'Routine minor repair notice issued.',
  },
  {
    id: 'INS-2026-096',
    businessId: 'BUS-1004',
    businessName: 'Taco Haven Food Truck',
    inspectorName: 'Officer Robert Vance',
    inspectorId: 'USR-INSP-03',
    type: 'Mobile Unit Renewal',
    date: '2026-07-10',
    time: '16:00',
    status: 'PASSED',
    score: 88,
    grade: 'B',
    riskCategory: 'HIGH',
    summary: 'Good overall compliance for mobile food prep.',
    violations: [
      { code: 'V-201', severity: 'MINOR', description: 'Water tank meter needs re-calibration.' }
    ],
    correctiveActionRequired: 'Calibrate water tank sensor.',
  },
  {
    id: 'INS-2026-095',
    businessId: 'BUS-1003',
    businessName: 'Fresh Harvest Organics',
    inspectorName: 'Officer Sarah Connor',
    inspectorId: 'USR-INSP-02',
    type: 'Routine Inspection',
    date: '2026-06-20',
    time: '10:00',
    status: 'PASSED',
    score: 98,
    grade: 'A',
    riskCategory: 'MEDIUM',
    summary: 'Flawless inspection score with zero critical violations.',
    violations: [],
    correctiveActionRequired: 'None. Certificate issued.',
  },
];

export const INITIAL_INSPECTORS = [
  {
    id: 'USR-INSP-01',
    name: 'David Kim',
    badgeNo: 'INS-882',
    district: 'Downtown & Harbor',
    email: 'david.kim@health.gov',
    phone: '+1 (555) 111-2233',
    activeAssignments: 5,
    completedThisMonth: 18,
    avgScoreGiven: 86.4,
    status: 'ACTIVE',
    rating: 4.9,
    certifications: ['HACCP Certified', 'Advanced Sanitation', 'Toxicology Specialist'],
  },
  {
    id: 'USR-INSP-02',
    name: 'Sarah Connor',
    badgeNo: 'INS-941',
    district: 'Eastside & Northside',
    email: 'sarah.connor@health.gov',
    phone: '+1 (555) 222-3344',
    activeAssignments: 4,
    completedThisMonth: 22,
    avgScoreGiven: 91.2,
    status: 'ACTIVE',
    rating: 4.8,
    certifications: ['Food Safety Lead', 'Epidemiology Audit'],
  },
  {
    id: 'USR-INSP-03',
    name: 'Robert Vance',
    badgeNo: 'INS-754',
    district: 'Harbor District',
    email: 'robert.vance@health.gov',
    phone: '+1 (555) 333-4455',
    activeAssignments: 3,
    completedThisMonth: 14,
    avgScoreGiven: 84.0,
    status: 'ACTIVE',
    rating: 4.7,
    certifications: ['Mobile Unit Specialist', 'Dairy & Meat Inspection'],
  },
  {
    id: 'USR-INSP-04',
    name: 'Elena Rostova',
    badgeNo: 'INS-612',
    district: 'Westside Heights',
    email: 'elena.rostova@health.gov',
    phone: '+1 (555) 444-5566',
    activeAssignments: 2,
    completedThisMonth: 16,
    avgScoreGiven: 89.5,
    status: 'ON_LEAVE',
    rating: 4.9,
    certifications: ['Biological Hazards Auditor', 'HACCP Certified'],
  },
];

export const INITIAL_ALERTS = [
  {
    id: 'ALT-1001',
    businessName: 'Ocean Catch Seafood Shack',
    businessId: 'BUS-1006',
    severity: 'CRITICAL',
    title: 'Emergency License Suspension',
    description: 'Cold storage failed holding temperatures for seafood. Immediate hazard warning issued.',
    date: '2026-07-29',
    status: 'OPEN',
    assignedTo: 'Officer David Kim',
  },
  {
    id: 'ALT-1002',
    businessName: 'Golden Dragon Express',
    businessId: 'BUS-1002',
    severity: 'HIGH',
    title: 'Hot Holding Temperature Failure',
    description: 'Repeated temperature deviations detected on hot buffet server unit.',
    date: '2026-07-28',
    status: 'IN_REVIEW',
    assignedTo: 'Officer Sarah Connor',
  },
  {
    id: 'ALT-1003',
    businessName: 'Taco Haven Food Truck',
    businessId: 'BUS-1004',
    severity: 'MEDIUM',
    title: 'Annual Permit Renewal Due',
    description: 'Mobile food safety operational permit expiring in 15 days.',
    date: '2026-07-20',
    status: 'OPEN',
    assignedTo: 'Officer Robert Vance',
  },
  {
    id: 'ALT-1004',
    businessName: 'Bistro Primavera',
    businessId: 'BUS-9988',
    severity: 'LOW',
    title: 'Routine Water Quality Sample Scheduled',
    description: 'Water filtration audit required for District 1 central grid.',
    date: '2026-07-15',
    status: 'RESOLVED',
    assignedTo: 'Officer David Kim',
  },
];

export const MONTHLY_TREND_DATA = [
  { month: 'Jan', inspections: 42, passed: 36, failed: 6, avgScore: 89 },
  { month: 'Feb', inspections: 48, passed: 41, failed: 7, avgScore: 87 },
  { month: 'Mar', inspections: 55, passed: 49, failed: 6, avgScore: 91 },
  { month: 'Apr', inspections: 60, passed: 52, failed: 8, avgScore: 88 },
  { month: 'May', inspections: 68, passed: 61, failed: 7, avgScore: 92 },
  { month: 'Jun', inspections: 74, passed: 65, failed: 9, avgScore: 86 },
  { month: 'Jul', inspections: 82, passed: 72, failed: 10, avgScore: 88 },
];

export const COMPLIANCE_DISTRIBUTION = [
  { name: 'Grade A (90-100%)', value: 58, color: '#22c55e' },
  { name: 'Grade B (80-89%)', value: 24, color: '#3b82f6' },
  { name: 'Grade C (70-79%)', value: 12, color: '#f59e0b' },
  { name: 'Grade F (<70%)', value: 6, color: '#ef4444' },
];

export const VIOLATION_CATEGORIES = [
  { category: 'Temperature Control', count: 38, percentage: 35 },
  { category: 'Sanitation & Hygiene', count: 28, percentage: 26 },
  { category: 'Cross Contamination', count: 18, percentage: 17 },
  { category: 'Equipment Maintenance', count: 14, percentage: 13 },
  { category: 'Pest Control', count: 10, percentage: 9 },
];
