/**
 * src/services/mockData.js
 * Comprehensive mock data engine for the Food Safety Inspection Monitor.
 * Updated with Indian names, GVMC wards, Visakhapatnam locations.
 */

export const INITIAL_BUSINESSES = [
  {
    id: 'BUS-1001',
    name: 'Sri Lakshmi Tiffins',
    type: 'South Indian Restaurant',
    licenseNo: 'FSSAI-VSP-2024-8831',
    owner: 'Sri. K. Venkata Rao',
    email: 'contact@srilakshmitiffins.in',
    phone: '+91 89123 45678',
    address: '4-52, MVP Colony, Ward 12, Visakhapatnam',
    district: 'MVP Colony Ward',
    riskLevel: 'HIGH',
    status: 'ACTIVE',
    healthScore: 94,
    grade: 'A',
    lastInspectionDate: '2026-07-15',
    nextInspectionDate: '2026-10-15',
    totalInspections: 12,
  },
  {
    id: 'BUS-1002',
    name: 'Annapurna Family Restaurant',
    type: 'Multi-Cuisine Restaurant',
    licenseNo: 'FSSAI-VSP-2024-9942',
    owner: 'Smt. P. Anand Lakshmi',
    email: 'info@annapurnarestaurant.in',
    phone: '+91 94567 89012',
    address: '12-3, Dwaraka Nagar, Ward 8, Visakhapatnam',
    district: 'Dwaraka Nagar Ward',
    riskLevel: 'HIGH',
    status: 'WARNING',
    healthScore: 74,
    grade: 'C',
    lastInspectionDate: '2026-07-28',
    nextInspectionDate: '2026-08-10',
    totalInspections: 18,
  },
  {
    id: 'BUS-1003',
    name: 'Sai Agro Fresh Provisions',
    type: 'Grocery & Provisions Store',
    licenseNo: 'FSSAI-VSP-2023-1102',
    owner: 'Sri. T. Rama Chandra Reddy',
    email: 'admin@saiagrofresh.in',
    phone: '+91 98765 43210',
    address: '7-11, Gajuwaka, Ward 3, Visakhapatnam',
    district: 'Gajuwaka Ward',
    riskLevel: 'MEDIUM',
    status: 'ACTIVE',
    healthScore: 98,
    grade: 'A',
    lastInspectionDate: '2026-06-20',
    nextInspectionDate: '2026-12-20',
    totalInspections: 8,
  },
  {
    id: 'BUS-1004',
    name: 'Rayalaseema Meals & Biryani',
    type: 'Mobile Food Unit',
    licenseNo: 'FSSAI-VSP-2025-0012',
    owner: 'Sri. B. Suresh Babu',
    email: 'rayalaseemameals@gmail.com',
    phone: '+91 70123 45678',
    address: 'Mobile Unit – RK Beach Promenade, Ward 7',
    district: 'RK Beach Ward',
    riskLevel: 'HIGH',
    status: 'ACTIVE',
    healthScore: 88,
    grade: 'B',
    lastInspectionDate: '2026-07-10',
    nextInspectionDate: '2026-09-10',
    totalInspections: 6,
  },
  {
    id: 'BUS-1005',
    name: 'Vijaya Bakery & Sweets',
    type: 'Bakery & Confectionery',
    licenseNo: 'FSSAI-VSP-2024-4410',
    owner: 'Smt. G. Saraswathi Devi',
    email: 'vijayabakery@gmail.com',
    phone: '+91 91234 56789',
    address: '3-6, Seethammadhara, Ward 5, Visakhapatnam',
    district: 'Seethammadhara Ward',
    riskLevel: 'LOW',
    status: 'ACTIVE',
    healthScore: 96,
    grade: 'A',
    lastInspectionDate: '2026-05-14',
    nextInspectionDate: '2026-11-14',
    totalInspections: 5,
  },
  {
    id: 'BUS-1006',
    name: 'Harbour Fish Market & Diner',
    type: 'Seafood Market & Diner',
    licenseNo: 'FSSAI-VSP-2023-7721',
    owner: 'Sri. M. Appalaswamy',
    email: 'harbourfish@vizagport.in',
    phone: '+91 88901 23456',
    address: '1-12, Fishing Harbour, Ward 15, Visakhapatnam',
    district: 'Fishing Harbour Ward',
    riskLevel: 'HIGH',
    status: 'SUSPENDED',
    healthScore: 58,
    grade: 'F',
    lastInspectionDate: '2026-07-29',
    nextInspectionDate: '2026-08-05',
    totalInspections: 22,
  },
  {
    id: 'BUS-1007',
    name: 'Sunrise Tea & Snacks Corner',
    type: 'Tea Stall & Snack Bar',
    licenseNo: 'FSSAI-VSP-2025-3329',
    owner: 'Sri. N. Venkateswara Rao',
    email: 'sunrisetea@gmail.com',
    phone: '+91 99876 54321',
    address: '8-45, Madhurawada, Ward 2, Visakhapatnam',
    district: 'Madhurawada Ward',
    riskLevel: 'LOW',
    status: 'ACTIVE',
    healthScore: 92,
    grade: 'A',
    lastInspectionDate: '2026-07-02',
    nextInspectionDate: '2027-01-02',
    totalInspections: 4,
  },
];

export const INITIAL_INSPECTIONS = [
  {
    id: 'INS-2026-099',
    businessId: 'BUS-1006',
    businessName: 'Harbour Fish Market & Diner',
    inspectorName: 'Health Inspector Ravi Kumar',
    inspectorId: 'USR-INSP-01',
    type: 'Emergency Re-inspection',
    date: '2026-07-29',
    time: '14:30',
    status: 'FAILED',
    score: 58,
    grade: 'F',
    riskCategory: 'HIGH',
    summary: 'Critical cold storage malfunction & cross-contamination detected.',
    violations: [
      { code: 'V-102', severity: 'CRITICAL', description: 'Walk-in freezer temp at 10°C (req. ≤ 4°C).' },
      { code: 'V-204', severity: 'MAJOR', description: 'Raw seafood stored above ready-to-eat items.' },
      { code: 'V-301', severity: 'MINOR', description: 'Missing disposable towels at handwashing sink.' }
    ],
    correctiveActionRequired: 'Immediate emergency closure until temperature system repair verification.',
  },
  {
    id: 'INS-2026-098',
    businessId: 'BUS-1002',
    businessName: 'Annapurna Family Restaurant',
    inspectorName: 'Health Inspector Smt. K. Sowjanya',
    inspectorId: 'USR-INSP-02',
    type: 'Routine Inspection',
    date: '2026-07-28',
    time: '11:15',
    status: 'WARNING',
    score: 74,
    grade: 'C',
    riskCategory: 'HIGH',
    summary: 'Inadequate food temperature monitoring during peak lunch service.',
    violations: [
      { code: 'V-108', severity: 'MAJOR', description: 'Hot hold counter measured at 50°C (req. ≥ 57°C).' },
      { code: 'V-402', severity: 'MINOR', description: 'Grease accumulation near exhaust hood filters.' }
    ],
    correctiveActionRequired: 'Re-inspection scheduled in 14 days.',
  },
  {
    id: 'INS-2026-097',
    businessId: 'BUS-1001',
    businessName: 'Sri Lakshmi Tiffins',
    inspectorName: 'Health Inspector Ravi Kumar',
    inspectorId: 'USR-INSP-01',
    type: 'Annual Routine',
    date: '2026-07-15',
    time: '09:45',
    status: 'PASSED',
    score: 94,
    grade: 'A',
    riskCategory: 'HIGH',
    summary: 'Excellent sanitation practices and spotless food prep surfaces.',
    violations: [
      { code: 'V-405', severity: 'MINOR', description: 'Floor tile chip near prep area needs repair.' }
    ],
    correctiveActionRequired: 'Routine minor repair notice issued.',
  },
  {
    id: 'INS-2026-096',
    businessId: 'BUS-1004',
    businessName: 'Rayalaseema Meals & Biryani',
    inspectorName: 'Health Inspector P. Narasimha Rao',
    inspectorId: 'USR-INSP-03',
    type: 'Mobile Unit Renewal',
    date: '2026-07-10',
    time: '16:00',
    status: 'PASSED',
    score: 88,
    grade: 'B',
    riskCategory: 'HIGH',
    summary: 'Good overall compliance for mobile food preparation.',
    violations: [
      { code: 'V-201', severity: 'MINOR', description: 'Water tank meter needs re-calibration.' }
    ],
    correctiveActionRequired: 'Calibrate water tank sensor within 7 days.',
  },
  {
    id: 'INS-2026-095',
    businessId: 'BUS-1003',
    businessName: 'Sai Agro Fresh Provisions',
    inspectorName: 'Health Inspector Smt. K. Sowjanya',
    inspectorId: 'USR-INSP-02',
    type: 'Routine Inspection',
    date: '2026-06-20',
    time: '10:00',
    status: 'PASSED',
    score: 98,
    grade: 'A',
    riskCategory: 'MEDIUM',
    summary: 'Flawless inspection score with zero critical violations.',
    violations: [],
    correctiveActionRequired: 'None. Certificate issued.',
  },
];

export const INITIAL_INSPECTORS = [
  {
    id: 'USR-INSP-01',
    name: 'Ravi Kumar',
    badgeNo: 'GVMC-INS-882',
    district: 'MVP Colony & RK Beach Ward',
    email: 'ravi.kumar@gvmc.gov.in',
    phone: '+91 94011 22334',
    activeAssignments: 5,
    completedThisMonth: 18,
    avgScoreGiven: 86.4,
    status: 'ACTIVE',
    rating: 4.9,
    certifications: ['FSSAI Certified', 'Advanced Sanitation', 'HACCP Specialist'],
  },
  {
    id: 'USR-INSP-02',
    name: 'Smt. K. Sowjanya',
    badgeNo: 'GVMC-INS-941',
    district: 'Dwaraka Nagar & Gajuwaka Ward',
    email: 'k.sowjanya@gvmc.gov.in',
    phone: '+91 94022 33445',
    activeAssignments: 4,
    completedThisMonth: 22,
    avgScoreGiven: 91.2,
    status: 'ACTIVE',
    rating: 4.8,
    certifications: ['Food Safety Lead', 'Epidemiology Audit'],
  },
  {
    id: 'USR-INSP-03',
    name: 'P. Narasimha Rao',
    badgeNo: 'GVMC-INS-754',
    district: 'Fishing Harbour & Port Ward',
    email: 'p.narasimha@gvmc.gov.in',
    phone: '+91 94033 44556',
    activeAssignments: 3,
    completedThisMonth: 14,
    avgScoreGiven: 84.0,
    status: 'ACTIVE',
    rating: 4.7,
    certifications: ['Mobile Unit Specialist', 'Seafood & Meat Inspection'],
  },
  {
    id: 'USR-INSP-04',
    name: 'Dr. S. Prasad',
    badgeNo: 'GVMC-INS-612',
    district: 'Seethammadhara & Madhurawada Ward',
    email: 's.prasad@gvmc.gov.in',
    phone: '+91 94044 55667',
    activeAssignments: 2,
    completedThisMonth: 16,
    avgScoreGiven: 89.5,
    status: 'ON_LEAVE',
    rating: 4.9,
    certifications: ['Biological Hazards Auditor', 'FSSAI Certified'],
  },
];

export const INITIAL_ALERTS = [
  {
    id: 'ALT-1001',
    businessName: 'Harbour Fish Market & Diner',
    businessId: 'BUS-1006',
    severity: 'CRITICAL',
    title: 'Emergency License Suspension',
    description: 'Cold storage failed holding temperatures for seafood. Immediate hazard warning issued per FSSAI norms.',
    date: '2026-07-29',
    status: 'OPEN',
    assignedTo: 'Health Inspector Ravi Kumar',
  },
  {
    id: 'ALT-1002',
    businessName: 'Annapurna Family Restaurant',
    businessId: 'BUS-1002',
    severity: 'HIGH',
    title: 'Hot Holding Temperature Failure',
    description: 'Repeated temperature deviations detected on hot food counter during peak hours.',
    date: '2026-07-28',
    status: 'IN_REVIEW',
    assignedTo: 'Health Inspector Smt. K. Sowjanya',
  },
  {
    id: 'ALT-1003',
    businessName: 'Rayalaseema Meals & Biryani',
    businessId: 'BUS-1004',
    severity: 'MEDIUM',
    title: 'Annual Permit Renewal Due',
    description: 'Mobile food safety operational permit expiring in 15 days. Renewal required.',
    date: '2026-07-20',
    status: 'OPEN',
    assignedTo: 'Health Inspector P. Narasimha Rao',
  },
  {
    id: 'ALT-1004',
    businessName: 'Sai Agro Fresh Provisions',
    businessId: 'BUS-1003',
    severity: 'LOW',
    title: 'Routine Water Quality Sample Scheduled',
    description: 'Water filtration audit required as per GVMC Ward 3 schedule.',
    date: '2026-07-15',
    status: 'RESOLVED',
    assignedTo: 'Health Inspector Ravi Kumar',
  },
];

export const MONTHLY_TREND_DATA = [
  { month: 'Jan', inspections: 42, passed: 36, failed: 6, avgScore: 89 },
  { month: 'Feb', inspections: 48, passed: 41, failed: 7, avgScore: 87 },
  { month: 'Mar', inspections: 55, passed: 49, failed: 6, avgScore: 91 },
  { month: 'Apr', inspections: 60, passed: 52, failed: 8, avgScore: 88 },
  { month: 'May', inspections: 68, passed: 61, failed: 7, avgScore: 92 },
  { month: 'Jun', inspections: 74, passed: 65, failed: 9, avgScore: 86 },
  { month: 'Jul', inspections: 82, passed: 72, failed: 10, avgScore: 88 },
];

export const COMPLIANCE_DISTRIBUTION = [
  { name: 'Grade A (90–100%)', value: 58, color: '#81B29A' },
  { name: 'Grade B (80–89%)', value: 24, color: '#3D405B' },
  { name: 'Grade C (70–79%)', value: 12, color: '#F2CC8F' },
  { name: 'Grade F (<70%)', value: 6, color: '#E07A5F' },
];

export const VIOLATION_CATEGORIES = [
  { category: 'Temperature Control', count: 38, percentage: 35 },
  { category: 'Sanitation & Hygiene', count: 28, percentage: 26 },
  { category: 'Cross Contamination', count: 18, percentage: 17 },
  { category: 'Equipment Maintenance', count: 14, percentage: 13 },
  { category: 'Pest Control', count: 10, percentage: 9 },
];
